<?php

///----------------------------------------------------------------------------------------------------->
$installed_dir = "/srv/www/lighttpd";
$webservicedirectories_server =  $_SERVER['SERVER_NAME']; /// Formula for a host with virtual hosts...
$MYUNPUBLISHEDSECRET = "youarehere";
$hostdirstructure = "$installed_dir/hosted/";
///----------------------------------------------------------------------------------------------------->
$g_installed_servicename = "Copious";
$g_installed_db_host = "localhost";
$g_installed_db_user = "root";
$g_installed_db_pass = 'simple';
///----------------------------------------------------------------------------------------------------->

?>
